"""add workflow_summaries table

Revision ID: 45596c4ef0fd
Revises: 8e3b57bbce22
Create Date: 2026-06-23 22:36:42.896922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '45596c4ef0fd'
down_revision: Union[str, None] = '8e3b57bbce22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('definition_hash', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_summaries')
    # ### end Alembic commands ###
