"""drop is_orphaned from workflows

Revision ID: 46c64d10d1ce
Revises: 45596c4ef0fd
Create Date: 2026-06-24 20:40:56.974908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '46c64d10d1ce'
down_revision: Union[str, None] = '45596c4ef0fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'is_orphaned')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('is_orphaned', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
